package model

/*
	@file	calendar.go
	@author	LoperLee
	@date	2019-11-20
*/

type AutoGenerated struct {
	Intent struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"intent"`
	UserRequest struct {
		Timezone string `json:"timezone"`
		Params   struct {
			IgnoreMe string `json:"ignoreMe"`
		} `json:"params"`
		Block struct {
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"block"`
		Utterance string      `json:"utterance"`
		Lang      interface{} `json:"lang"`
		User      struct {
			ID         string `json:"id"`
			Type       string `json:"type"`
			Properties struct {
			} `json:"properties"`
		} `json:"user"`
	} `json:"userRequest"`
	Bot struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"bot"`
	Action struct {
		Name        string      `json:"name"`
		ClientExtra interface{} `json:"clientExtra"`
		Params      struct {
			Date string `json:"date"`
		} `json:"params"`
		ID           string `json:"id"`
		DetailParams struct {
			Date struct {
				Origin    string `json:"origin"`
				Value     string `json:"value"`
				GroupName string `json:"groupName"`
			} `json:"date"`
		} `json:"detailParams"`
	} `json:"action"`
}

func GetCalendar() {

}
